Puchase ticket UI implement in progress
GDG-W/Hogwarts pull request #14
Opened 2024-07-23 01:42 UTC by Tobipeters

- Reuseable modal component 
- -Purchase ticket component UIs

2024-07-23 22:31 UTC, TemitopeAsama commented on src/assets/svg.tsx
I don't understand why you created a custom SVG component when SVGs can simply be imported as React components?

2024-07-23 22:32 UTC, TemitopeAsama commented on package.json
Please use custom ports on your end when running the dev command. Let's keep it at 3000 on the project.

2024-07-23 22:35 UTC, TemitopeAsama commented on src/components/modal/modal.module.scss
Please use the breakpoints from the _brakpoints.scss files to reduce ambiguity. Instantiate your custom breakpoints on the root stylesheet.

2024-07-23 22:36 UTC, TemitopeAsama commented on src/components/purchase-ticket/components/checkout/checkout.module.scss
Fix issue with breakpoints here too.

2024-07-23 22:36 UTC, TemitopeAsama commented on src/components/purchase-ticket/ticket.module.scss
Issue with breakpoints here too.

2024-07-23 22:37 UTC, TemitopeAsama commented on src/components/purchase-ticket/ticket.module.scss
Also, I don't see the forms and all.

2024-07-23 22:37 UTC, TemitopeAsama requested changes
Please fix issues as outlined as soon as you can. Thanks.

2024-07-24 16:02 UTC, Tobipeters commented on src/assets/svg.tsx
This has been resolved

2024-07-24 16:02 UTC, Tobipeters commented on package.json
Resolved

2024-07-24 16:02 UTC, Tobipeters commented on src/components/modal/modal.module.scss
Resolved

2024-07-24 16:02 UTC, Tobipeters commented on src/components/purchase-ticket/components/checkout/checkout.module.scss
Resolved

2024-07-24 16:03 UTC, Tobipeters commented on src/components/purchase-ticket/ticket.module.scss
Resolved

2024-07-24 16:03 UTC, Tobipeters commented on src/components/purchase-ticket/ticket.module.scss
Work in progress

2024-07-27 21:39 UTC, TemitopeAsama approved these changes

2024-07-28 20:39 UTC, merged